name: REBUILD Rom MIUI by chamchamfy & kakathic
on: 
  workflow_dispatch:
jobs:
  build:
    name: 'Xem quá trình'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Xem thông báo'
        run: |
          chmod -R 777 .github/bin/*
          export PATH="$GITHUB_WORKSPACE/.github/bin:$PATH"
          chmod -R 777 .github/*.sh
          . .github/Chay.sh
      - name: Upload rom
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: Up
          tag_name: Up
          files: rom.zip
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 0
