name: REBUILD rom MIUI by CC
on: 
  workflow_dispatch:
jobs:
  build:
    name: 'Xem quá trình'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Xem thông báo'
        run: |
          chmod -R 777 .github/bin/*
          export PATH="$GITHUB_WORKSPACE/.github/bin:$PATH"
          chmod -R 777 .github/*.sh
          . .github/install.sh
      - name: 'Upload Rom'
        uses: actions/upload-artifact@v3
        with:
          name: Zom_Edit
          path: .github/lib/Flash_2in1/*
          retention-days: 2
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 0