name: CI

on: 
  push:
    branches: [ "Vip" ]
  pull_request:
    branches: [ "Vip" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate package
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: package
          flags: '-si --noconfirm'
          namcap: false
      - name: Run Shell
        run: |
          chmod -R 777 *.sh
          . install.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Zom_Edit
          path: bin.txt
          retention-days: 5
