name: CI

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Shell
        run: |
          chmod -R 777 bin/*
          export PATH="$GITHUB_WORKSPACE/bin:$PATH"
          chmod -R 777 *.sh
          . install.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Zom_Edit
          path: bin.txt
          retention-days: 5
