name: CI
on:
  push:
    branches: [ "Vip" ]
  pull_request:
    branches: [ "Vip" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Shell
        run: |
          chmod -R 777 *.sh
          . install.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Zom_Edit
          path: bin.txt
          retention-days: 5
