name: REBUILD Rom MIUI by chamchamfy & kakathic
on: 
  workflow_dispatch:
    inputs:
      URL:
        description: 'Hãy điền đường dẫn url của link rom để tải xuống'
        required: true
        default: 'https://bigota.d.miui.com/V13.0.7.0.SKHCNXM/miui_ALIOTH_V13.0.7.0.SKHCNXM_98b397a7dc_12.0.zip'
      SIZE:
        description: 'Kích cỡ phân vùng super'
        required: true
        default: '8.5'
jobs:
  build:
    name: 'Xem quá trình'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Xem thông báo'
        env:
          URL: ${{ inputs.URL }}
          SIZE: ${{ inputs.SIZE }}
        run: |
          chmod -R 777 .github/bin/*
          export PATH="$GITHUB_WORKSPACE/.github/bin:$PATH"
          chmod -R 777 .github/*.sh
          bash .github/Chay.sh
      - name: Upload rom
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: Download rom
          tag_name: Up
          files: Up/*
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 0
